repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use a versão mais recente
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-return
          - flake8-isort
          - flake8-quotes
          - flake8-builtins
          - flake8-variables-names